FROM nginx:latest

ADD config/nginx/sites-enabled/default.conf  /etc/nginx/sites-enabled/default.conf
ADD config/nginx/nginx.conf  /etc/nginx/nginx.conf
ADD config/nginx/ssl  /etc/nginx/ssl
ADD config/nginx/auth  /etc/nginx/auth
